version: 1.0.{build}

clone_folder: c:\dev\lib-template-cmake

os:
    - Visual Studio 2013
    - Visual Studio 2015
    - Visual Studio 2017

install:

build:

build_script:
    # Build the library
    - cd c:\dev\lib-template-cmake
    - md build
    - cd build
    - cmake -DBUILD_TESTING:BOOL=ON -DCMAKE_CXX_FLAGS:STRING="/W4" ..
    # Build the library for Release and Debug
    - cmake --build . --config Debug
    - cmake --build . --config Release

after_build:
    # Install only release
    - cmake --build C:\dev\lib-template-cmake\build --config Release --target INSTALL

test_script:
    - ctest -C Debug -VV
    - ctest -C Release -VV
